version: '3'
tasks:
  setup:
    desc: Install dependencies
    cmds:
    - npm install
  run:
    desc: Run the app from source
    cmds:
    - npm start
  package:
    desc: Package the app as a binary for distribution
    cmds:
    - npm run make